### ISSUE TITLE
Error : 'tree' must be ultrametric

### ISSUE THREAD

**Issue by UzmaSalam** [richfitz/diversitree#17]
I'm using Rsudio and when I run the script of GeoSSE I got this error:
Error in check.tree(tree) : 'tree' must be ultrametric

Although the tree is ultrametric. 
Thank you!

**Comment by richfitz** [comment]
Test your tree with `ape::is.ultrametric`, it probably is not actually ultrametric.

**Comment by UzmaSalam** [comment]
yes it comes out with [False]
How could I make this nearly ultrametric tree into ultrametric tree?
Thank you!

**Comment by richfitz** [comment]
I don't know - it varies by your tree making software.  The ape package may have something that can help perhaps.

**Comment by UzmaSalam** [comment]
Yes I found one using libraries "ape" and "phangorn, and function is:
tr<-nnls.tree(cophenetic(tree),tree, rooted=TRUE,trace=0)

Thank you!

**Comment by richfitz** [comment]
Great :smil
