### ISSUE TITLE
mcmc run

### ISSUE THREAD

**Issue by UzmaSalam** [richfitz/diversitree#18]
I got this error when I ran mcmc for best fitted model which is 'full.4c'
Error in mcmc(model.4c.full, p.4c.mcmc.full, nsteps = 100, prior = prior,  : 
  object 'model.4c.full' not found

Thank you!

**Comment by richfitz** [comment]
This error means that your object `model.4c.full` cannot be found. I expect that `exists("model.4c.full")` will confirm it does not exist.

**Comment by UzmaSalam** [comment]
Now this error:
Error in f(...) : could not find function "lik"
is it possible if you could see my script?
Thank you!

**Comment by richfitz** [comment]
No, I'm afraid not - the issues are certainly coming from your code, and I can't provide technical support for users of the package.

**Comment by UzmaSalam** [comment]
ok thank you!
