### ISSUE TITLE
Minor bug when node is not matched in get.descendants

### ISSUE THREAD

**Issue by szhan** [richfitz/diversitree#38]
When calling ``get.descendants()`` if the node is not matched, the following error happens.
`Error in sprintf("Node '%s' not found in tree") : too few arguments`

This is due to a small typo when calling ``sprintf()``.
`stop(sprintf("Node '%s' not found in tree"), node)`

It should be
`stop(sprintf("Node '%s' not found in tree", node))`

**Comment by richfitz** [comment]
Thanks - this package is not really maintained any more aside from keeping it on CRAN, but this was nice and easy to fix :)
